server:
  port: 8091

spring:
  data:
    mongodb:
      #user: test
      #password: passwordvalue
      #uri: mongodb://host:27017/CustomersDb
      database: Customersdb
      host: localhost
      port: 27017